services:
  workflow:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "/home/zheng/easier-all/data-all:/data/"
      - "/home/zheng/.netrc:/root/.netrc"
      - ".:/cdl_training_data"
